name: mitch2
favicon: null
layout_spectrum: 0.6810784577392042
typography_spectrum: 0.23986374586820602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9523594239726663
  lightness: 0.06208979384973645
  saturation: 0.7542527348268777
  rhythmicContrast: 0.6938840858638287
purpose: []
